### ISSUE TITLE
Shortcode does not work

### ISSUE THREAD

**Issue by fefed22** [iansvo/nova-select-all-occurrences#1]
Hello, 

i'm in Nova 7 and the shortcode does not work....
How check the good installation ?

Best regards

**Comment by fefed22** [comment]
i've found the issue, the shortcode is not : 
Cmd + Option + G. 
but
Ctrl + Cmd + G.

**Comment by iansvo** [comment]
Thanks for letting me know. I've seen this previously but I'll be sure to get that updated.
